export const dataValues={
    "articles":[
        {
          "id":0,
          "heading":"Northeastern University",
          "body":[{"section":"About","topic":"Northeastern University (NU or NEU) is a private research university in Boston, Massachusetts, established in 1898. It is categorized as an R1 institution (Doctoral Universities: Highest Research Activity) by the Carnegie Classification of Institutions of Higher Education.[4] The university offers undergraduate and graduate programs on its main campus in Boston. The university has satellite campuses in Charlotte, North Carolina; Seattle, Washington; San Jose, California; and Toronto, Canada, that exclusively offer graduate degrees. Northeastern recently purchased the New College of the Humanities in London and plans to open an additional campus in Vancouver, Canada. The university's enrollment is approximately 18,000 undergraduate students and 8,000 graduate students"},
          {"section":"History","topic":"The Evening Institute for Younger Men, located at the Huntington Avenue YMCA, held its first class on October 3, 1898, starting what would transform into Northeastern University over the course of four decades. The School of Law was formally established that year with the assistance of an Advisory Committee, consisting of Dean James Barr Ames of the Harvard University School of Law, Dean Samuel Bennett of the Boston University School of Law, and Judge James R. Dunbar. In 1903, the first Automobile Engineering School in the country was established followed by the School of Commerce and Finance in 1907. Day classes began in 1909. In 1916, a bill was introduced into the Massachusetts Legislature to incorporate the institute as Northeastern College. After considerable debate and investigation, it was passed in March 1916"}]
        },
        {
          "id":1,
          "heading":"Boston",
          "body":[{"section":"About Boston","topic":"Boston (UK: /ˈbɒstən/, US: /ˈbɔːstən/) is the      capital and most populous city of the Commonwealth of Massachusetts in the United States, and the 21st most populous city in the United States. The city proper covers 49 square miles (127 km2) with an estimated population of 694,583 in 2018, also making it the most populous city in New England. Boston is the seat of Suffolk County as well, although the county government was disbanded on July 1, 1999. The city is the economic and cultural anchor of a substantially larger metropolitan area known as Greater Boston, a metropolitan statistical area (MSA) home to a census-estimated 4.8 million people in 2016 and ranking as the tenth-largest such area in the country. As a combined statistical area (CSA), this wider commuting region is home to some 8.2 million people, making it the sixth most populous in the United States"},
                  {"section":"Boston Geography ","topic":"Boston has an area of 89.63 square miles (232.1 km2)—48.4 square miles (125.4 km2) (54%) of land and 41.2 square miles (106.7 km2) (46%) of water. The city's official elevation, as measured at Logan International Airport, is 19 ft (5.8 m) above sea level. The highest point in Boston is Bellevue Hill at 330 feet (100 m) above sea level, and the lowest point is at sea level. Situated onshore of the Atlantic Ocean, Boston is the only state capital in the contiguous United States with an oceanic shoreline."},
                  {"section":"Boston Sports","topic":"Boston has teams in the four major North American professional sports leagues plus Major League Soccer, and, as of 2019, has won 39 championships in these leagues. It is one of seven cities (along with Chicago, Detroit, Los Angeles, New York, Philadelphia and St. Louis) to have won championships in all four major sports. It has been suggested that Boston is the new TitleTown, USA, as the city's professional sports teams have won twelve championships since 2001: Patriots (2001, 2003, 2004, 2014, 2016 and 2018), Red Sox (2004, 2007, 2013, and 2018), Celtics (2008), and Bruins (2011). This love of sports made Boston the United States Olympic Committee's choice to bid to hold the 2024 Summer Olympic Games, but the city cited financial concerns when it withdrew its bid on July 27, 2015"}]
        },
        {
          "id":2,
          "heading":"Massachusetts",
          "body":[{"section":"About Massachusetts","topic":"Massachusetts (/ˌmæsəˈtʃuːsɪts/ (About this soundlisten), /-zɪts/), officially known as the Commonwealth of Massachusetts, is the most populous state in the New England region of the northeastern United States. It borders on the Atlantic Ocean to the east, the states of Connecticut and Rhode Island to the south, New Hampshire and Vermont to the north, and New York to the west. The capital of Massachusetts is Boston, which is also the most populous city in New England. Massachusetts is the most urban state in the United States with 85% of it's 7 Million residents living in the Greater Boston metropolitan area, a region influential upon American history, academia, and industry.[41] Originally dependent on agriculture, fishing and trade, Massachusetts was transformed into a manufacturing center during the Industrial Revolution. During the 20th century, Massachusetts's economy shifted from manufacturing to services. Modern Massachusetts is a global leader in biotechnology, engineering, higher education, finance, and maritime trade."},
                  {"section":"Economic","topic":"The United States Bureau of Economic Analysis estimates that the Massachusetts gross state product in 2017 was US$527 billion.[206] The per capita personal income in 2012 was $53,221, making it the third-highest state in the nation.[207] As of January 2020, Massachusetts general minimum wage in the state is $12.75 per hour while the minimum wage for tipped workers is $4.95 an hour In 2015, twelve Fortune 500 companies were located in Massachusetts: Liberty Mutual, Massachusetts Mutual Life Insurance Company, TJX Companies, General Electric, Raytheon, American Tower, Global Partners, Thermo Fisher Scientific, State Street Corporation, Biogen, Eversource Energy, and Boston Scientific.[209] CNBC's list of Top States for Business for 2014 has recognized Massachusetts as the 25th-best state in the nation for business,[210] and for the second year in a row the state was ranked by Bloomberg as the most innovative state in America.[211] According to a 2013 study by Phoenix Marketing International, Massachusetts had the sixth-largest number of millionaires per capita in the United States, with a ratio of 6.73 percent.[212] Billionaires living in the state include past and present leaders (and related family) of local companies such as Fidelity Investments, New Balance, Kraft Group, Boston Scientific, and the former Continental Cablevision.Massachusetts has three foreign-trade zones, the Massachusetts Port Authority of Boston, the Port of New Bedford, and the City of Holyoke.[214] Boston-Logan International Airport is the busiest airport in New England, serving 33.4 million total passengers in 2015, and witnessing rapid growth in international air traffic since 2010"},
                  {"section":"Transportation","topic":"Massachusetts has 10 regional metropolitan planning organizations and three non-metropolitan planning organizations covering the remainder of the state; statewide planning is handled by the Massachusetts Department of Transportation. Transportation is the single largest source of greenhouse gas emissions by economic sector in Massachusetts. Amtrak operates inter-city rail, including the high-speed Acela service to cities such as Providence, New Haven, New York City, and Washington, DC from South Station. From North Station the Amtrak Downeaster serves Portland, Maine and Brunswick, Maine.[251] Amtrak also runs east-west from Boston South Station to Worcester, Springfield, and eventually Chicago, Illinois; and north-south from the Pioneer Valley to New Haven, Connecticut via Hartford. Amtrak carries more passengers between Boston and New York than all airlines combined (about 54% of market share in 2012).[252] but has infrequent trips to other cities. There, more frequent intercity service is provided by private bus carriers, including Peter Pan Bus Lines (headquartered in Springfield), Greyhound Lines, OurBus and BoltBus. Various Chinatown bus lines depart for New York from South Station in Boston. MBTA Commuter Rail services run throughout the larger Greater Boston area, including service to Worcester, Fitchburg, Haverhill, Newburyport, Lowell, and Plymouth.[253] This overlaps with the service areas of neighboring regional transportation authorities. As of the summer of 2013 the Cape Cod Regional Transit Authority in collaboration with the MBTA and the Massachusetts Department of Transportation (MassDOT) is operating the CapeFLYER providing passenger rail service between Boston and Cape Cod"}]
        }
        ]
}